Resources:
  MySQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "hhz-queue"
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: hzhuang-topic
      TopicName: hzhuang-topic
      Subscription:
        - Endpoint: hzhuang@thoughtworks.com
          Protocol: email
        - Endpoint: !GetAtt MySQS.Arn
          Protocol: sqs
  TriggerSNSEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: The rule use to trigger sns
      ScheduleExpression: rate(1 minute)
      Targets:
        - Arn: !Ref SNSTopic
          Id: trigger-sns
