Resources:
  MyDeadLetterQueue: 
    Type: AWS::SQS::Queue
  MySQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "hhz-queue"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MyDeadLetterQueue.Arn
        maxReceiveCount: 5
      MessageRetentionPeriod: 104800
      VisibilityTimeout: 300
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: hzhuang-topic
      TopicName: hzhuang-topic
      Subscription:
        - Endpoint: hzhuang@thoughtworks.com
          Protocol: email
        - Endpoint: !GetAtt MySQS.Arn
          Protocol: sqs
  TriggerSNSEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: The rule use to trigger sns
      ScheduleExpression: rate(1 minute)
      Targets:
        - Arn: !Ref SNSTopic
          Id: trigger-sns
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues: 
        - !Ref MySQS
      PolicyDocument:
        Statement:
          -
            Action:
              - "SQS:SendMessage" 
              - "SQS:ReceiveMessage"
            Resource: !GetAtt MySQS.Arn
            Effect: Allow
            Principal: "*"
            Sid: allow-sns-messages
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SNSTopic
  MyFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: hzhuang-bucket
        S3Key: function.zip
      FunctionName: hzhuang-lambda
      Handler: "index.handler"
      Role: arn:aws:iam::494526681395:role/hzhuang-aws-training-role
      Runtime: "python3.7"
  PermissionForSQSToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref MyFunction
      Action: "lambda:InvokeFunction"
      Principal: "*"
      SourceArn: !GetAtt MySQS.Arn
  LambdaSQSMapper:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt MySQS.Arn
      FunctionName: !Ref MyFunction
Outputs: 
  MyQueueURL: 
    Description: "URL of source queue"
    Value: 
      Ref: "MySQS"
  MyQueueARN: 
    Description: "ARN of source queue"
    Value: 
      Fn::GetAtt:
        - "MySQS"
        - "Arn"
  DeadLetterQueueURL: 
    Description: "URL of dead-letter queue"
    Value: 
      Ref: "MyDeadLetterQueue"
  DeadLetterQueueARN: 
    Description: "ARN of dead-letter queue"
    Value: 
      Fn::GetAtt: 
        - "MyDeadLetterQueue"
        - "Arn"
  TopicRef:
    Description: "Ref of SNSTopic"
    Value: !Ref SNSTopic