Resources:
  SnsSubscriber:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: hzhuang-sns-subscriber-c
      Description: sns subscriber
      Runtime: nodejs12.x
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = function(event) {
            console.log(JSON.stringify(event, null, 2))
            return "Done"
          };
      Role: arn:aws:iam::494526681395:role/for-aws-training
  SnsSource:
    Type: AWS::SNS::Topic
    Properties: 
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt SnsSubscriber.Arn
      TopicName: hzhuang-topic
  InvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref SnsSubscriber
      Principal: sns.amazonaws.com
