Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: hzhuang-hello-world-c
      Description: Lambda Function of nodejs12.x.
      Runtime: nodejs12.x
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = function(event, context) {
            console.log("event")
            return "Done"
          };
      Role: arn:aws:iam::494526681395:role/for-aws-training
Outputs:
  LambdaFunctionName:
    Value:
      Ref: LambdaFunction