Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: hzhuang-send-metrics
      Description: send metrics
      Runtime: nodejs12.x
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = function(event) {
            console.error("Hello, world!");
            return "Done";
          };
      Role: arn:aws:iam::494526681395:role/for-aws-training
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "rate(1 minute)"
      State: "ENABLED"
      Name: "hzhuang-send-metric-scheduler"
      Targets:
        - 
          Arn: 
            Fn::GetAtt: 
              - "LambdaFunction"
              - "Arn"
          Id: "send"
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "LambdaFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "ScheduledRule"
          - "Arn"
  AlarmSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: "hzhuang@thoughtworks.com"
          Protocol: email
  MetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaFunction}
      FilterPattern: ERROR
      MetricTransformations:
        - MetricNamespace: hzhuang
          MetricName: errorCount
          MetricValue: 1
  MetricsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: hzhuangMetricsAlert
      MetricName: errorCount
      Namespace: hzhuang
      Statistic: Maximum
      AlarmActions:
        - Ref: AlarmSNSTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 2
      EvaluationPeriods: 1
      Statistic: Sum
      Period: 180
Outputs:
  LambdaFunctionName:
    Value:
      Ref: LambdaFunction