Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: hzhuang-process-s3-c
      Description: process s3 bucket
      Runtime: nodejs12.x
      Handler: index.handler
      Code:
        S3Bucket: aws-training-hzhuang
        S3Key: process-s3.zip
      Role: arn:aws:iam::494526681395:role/for-aws-training
  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "rate(1 minute)"
      State: "ENABLED"
      Name: "hzhuang-scheduler-for-s3-processor"
      Targets:
        - 
          Arn: 
            Fn::GetAtt: 
              - "LambdaFunction"
              - "Arn"
          Id: "c5d49e40-345b-4bd8-8bf9-fc242cea65b7"
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "LambdaFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "ScheduledRule"
          - "Arn"
Outputs:
  LambdaFunctionName:
    Value:
      Ref: LambdaFunction